services:
  - type: web
    name: resume-django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: resume-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: resume-valkey
          type: redis

  - type: worker
    name: celery-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A core worker --loglevel=info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: resume-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: resume-valkey
          type: redis

  - type: redis
    name: resume-valkey
    ipAllowList: []
    plan: free

databases:
  - name: resume-db
    plan: free
